development:
  rpc_host: localhost
  rpc_port: 8102
  rpc_whitelist: "*"
  minerthreads: 2
  datadir: /tmp/embark2
  mine_when_needed: true
  gas_limit: 1000000
  gas_price: 10000000000000
  console: false
  account:
    init: true
    password: config/password
staging:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  datadir: default
  network_id: 0
  console: true
  account:
    init: false
    address: 
